<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '7',
    'typeid' => '0',
    'title' => 'downloads',
    'style' => '',
    'thumb' => '',
    'keywords' => 'downloadsdownloads',
    'description' => 'downloads',
    'posids' => '0',
    'url' => 'http://localhost/taomujiannew/index.php?m=content&c=index&a=show&catid=7&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1462601308',
    'updatetime' => '1462601417',
    'systems' => 'Win2000/WinXP/Win2003',
    'copytype' => '免费版',
    'language' => '英文',
    'classtype' => '',
    'version' => '',
    'filesize' => '未知',
    'stars' => '',
    'hitsid' => 'c-2-1',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>