<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '12',
    'typeid' => '0',
    'title' => 'products1',
    'style' => '',
    'thumb' => 'http://localhost/taomujiannew/uploadfile/2016/0509/20160509014430951.jpeg',
    'keywords' => 'products1 keywords',
    'description' => 'products1 contents',
    'posids' => '0',
    'url' => 'http://localhost/taomujiannew/index.php?m=content&c=index&a=show&catid=12&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1462600810',
    'updatetime' => '1462777676',
    'hitsid' => 'c-1-1',
    'views' => '20',
    'yesterdayviews' => '0',
    'dayviews' => '18',
    'weekviews' => '18',
    'monthviews' => '20',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '12',
    'typeid' => '0',
    'title' => 'pro2 title',
    'style' => '',
    'thumb' => 'http://localhost/taomujiannew/uploadfile/2016/0509/20160509033319159.jpeg',
    'keywords' => 'pro2 key',
    'description' => 'pro2 important',
    'posids' => '0',
    'url' => 'http://localhost/taomujiannew/index.php?m=content&c=index&a=show&catid=12&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1462779121',
    'updatetime' => '1462779244',
    'hitsid' => 'c-1-3',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>